회원가입 페이지를 제작했습니다
EntryDSM/Baskin-Robbins pull request #5
Opened 2019-07-25 05:58 UTC by Chaeeun-Lee

2019-07-29 05:40 UTC, soheejang15 commented on pickin-front/src/component/SignUp/clauseadmit/index.tsx
> +import { checkedIcon } from "./../../../assets/index";
파일명이 index로 되어있는 경우엔 경로를 상위 폴더인 assets까지만 명시해도 임포트 되는 것으로 알고 있어요!

2019-07-30 04:48 UTC, Chaeeun-Lee commented on pickin-front/src/component/SignUp/clauseadmit/index.tsx
> +import { checkedIcon } from "./../../../assets/index";
수정하겠습니다!

2019-07-30 05:13 UTC, junu126 requested changes

2019-07-30 05:13 UTC, junu126 commented on pickin-front/src/component/SignUp/clauseadmit/index.tsx
> +  setChecked(e: boolean): void;
`boolean`형의 변수의 네이밍명은 앞에 `is`를 붙여주는 것이 좋다고
책 `CleanCode`에서 말하고 있습니다!

`isChecked` / `setIsChecked`로 바꾸는 것이 좋을 거 같아요

2019-07-30 05:13 UTC, junu126 commented on pickin-front/src/component/SignUp/inputbox/index.tsx
> +  checkAgency: boolean;
네이밍명 변경 바랍니다.

2019-07-30 05:13 UTC, junu126 commented on pickin-front/src/component/SignUp/inputbox/index.tsx
> +      {checkAgency ? <S.CheckAgencyBtn>기관 확인</S.CheckAgencyBtn> : ""}
`checkAgency`가 true일때만 반환되고 false일때는 아무런 동작을 하지 않을때에는 다음과 같이 사용할 수 있습니다.
```ts
{isCheckAgency && <S.CheckAgencyBtn>기관 확인</S.CheckAgencyBtn>}
```

2019-07-30 05:13 UTC, junu126 commented on pickin-front/src/pages/SignUp/AgencySignUp/index.tsx
> +  const [checked, setChecked] = React.useState<boolean | null>(false);
네이밍 변경해주세요.

그리고 유니온 타입으로 `null`을 준 이유가 있을까요??

2019-07-30 05:13 UTC, junu126 commented on pickin-front/src/pages/SignUp/AgencySignUp/index.tsx
> +      <S.SignUpFormLogo src={pickinLogo} />
`alt`추가해 주세요.

2019-07-30 05:13 UTC, junu126 commented on pickin-front/src/pages/SignUp/InterviewerSignUp/index.tsx
> +  const [checked, setChecked] = React.useState<boolean | null>(false);
네이밍 확인해주세여

2019-07-30 05:13 UTC, junu126 commented on pickin-front/src/pages/SignUp/InterviewerSignUp/index.tsx
> +import { InputBox, ClauseAdmit } from "./../../../component/index";
폴더 구조에서 `index.ts 및 index.tsx`는 import해오지 않아도 자동으로 import처리가 됩니다. 가독성을 위해 제거해주세요.

2019-07-30 05:13 UTC, junu126 commented on pickin-front/src/pages/SignUp/style.ts
> +  inputCheck: boolean;
네이밍 확인 바랍니다.

2019-07-30 05:23 UTC, Chaeeun-Lee commented on pickin-front/src/component/SignUp/clauseadmit/index.tsx
> +  setChecked(e: boolean): void;
수정하겠습니다

2019-07-30 05:23 UTC, Chaeeun-Lee commented on pickin-front/src/component/SignUp/inputbox/index.tsx
> +  checkAgency: boolean;
수정하겠습니다!

2019-07-30 05:24 UTC, Chaeeun-Lee commented on pickin-front/src/component/SignUp/inputbox/index.tsx
> +      {checkAgency ? <S.CheckAgencyBtn>기관 확인</S.CheckAgencyBtn> : ""}
수정하겠습니다

2019-07-30 05:29 UTC, Chaeeun-Lee commented on pickin-front/src/pages/SignUp/AgencySignUp/index.tsx
> +  const [checked, setChecked] = React.useState<boolean | null>(false);
타입과 관련된 오류가 떠서 구글링 한 뒤 작성했는데 `null`을 줄 문제가 아니었더라고요 ㅠㅠ 수정하겠습니다

2019-07-30 05:30 UTC, Chaeeun-Lee commented on pickin-front/src/pages/SignUp/AgencySignUp/index.tsx
> +      <S.SignUpFormLogo src={pickinLogo} />
추가하겠습니다!

2019-07-30 05:30 UTC, Chaeeun-Lee commented on pickin-front/src/pages/SignUp/InterviewerSignUp/index.tsx
> +  const [checked, setChecked] = React.useState<boolean | null>(false);
알겠습니다

2019-07-30 05:31 UTC, Chaeeun-Lee commented on pickin-front/src/pages/SignUp/InterviewerSignUp/index.tsx
> +import { InputBox, ClauseAdmit } from "./../../../component/index";
제거하겠습니다

2019-07-30 05:31 UTC, Chaeeun-Lee commented on pickin-front/src/pages/SignUp/style.ts
> +  inputCheck: boolean;
알겠습니다

2019-07-30 05:44 UTC, merged