로그인 페이지를 만들었습니다.
EntryDSM/Baskin-Robbins pull request #6
Opened 2019-08-20 10:10 UTC by Chaeeun-Lee

2019-08-20 10:24 UTC, engolder commented on pickin-front/src/pages/SignIn/style.ts
> +  height: 100vh;
이거 app.tsx에서 높이 100vh로 해놓는컴포넌트 하나 만들어놓고 display flex로 자식한테 height 계속 넘겨주셈 어차피 모든 페이지에서 100vh쓸거아님??

2019-08-20 10:24 UTC, engolder commented on pickin-front/src/pages/SignIn/style.ts
> +  border: solid 0.5px #606060;
이거 소희한테도 말했는데 크롬에서는 1px미만이 안돼요 디자이너하고 협상하세여

2019-08-20 10:24 UTC, engolder commented on pickin-front/src/pages/SignIn/style.ts
> +  opacity: 0.9;
디자인을 못보긴했는데 이거 뭔가 색 연하게만드려고 이렇게한거같은데 한번 디자이너한테물어봐보셈 그런거라면 color랑 bg color주는게 나을듯

2019-08-20 10:24 UTC, engolder commented on pickin-front/src/pages/SignIn/style.ts
> +  background-color: ${mainColor};
이렇게 Themeing을 할거면 아예 모든 컴포넌트다하고 모든 색상에 다하는게 나을듯. #ffffff포함해서

2019-08-20 10:24 UTC, engolder commented on pickin-front/src/pages/SignIn/style.ts
> +  & p {
자식선택자를 쓸거면
‘> p’
이렇게 하는게 좋을듯 그리고 &저거 필요없을걸

2019-08-20 10:24 UTC, engolder commented on pickin-front/src/pages/index.ts
> +export { default as SignIn } from "./SignIn";
Eof line

2019-08-20 10:38 UTC, junu126 commented on pickin-front/src/pages/SignIn/style.ts
> +  height: 100vh;
와 미쳤네 똑똑;

2019-08-20 10:39 UTC, junu126 commented on pickin-front/src/pages/SignIn/style.ts
> +  opacity: 0.9;
나는 이거 16진수 rgb 변환기 써서 rgba에 투명도 달아줬음..
전부 다...

2019-08-20 10:42 UTC, junu126 requested changes

2019-08-20 10:42 UTC, junu126 commented on pickin-front/src/pages/SignIn/index.tsx
> +    <S.CreateAccountText>Do not have an account?<Link to="/signup"><p>Create Account</p></Link>
Lint 적용이 안된건강

2019-08-20 10:42 UTC, junu126 commented on pickin-front/src/pages/index.ts
> +export { default as SignIn } from "./SignIn";
`Eof` = "End Of File"

2019-08-20 10:43 UTC, junu126 approved these changes

2019-08-21 10:17 UTC, Chaeeun-Lee commented on pickin-front/src/pages/SignIn/style.ts
> +  height: 100vh;
app.tsx에 100vh를 주면 자식에서는  flex안써도 그냥 height: 100%로 높이 맞출 수 있는 거 아닌가요?
그리구 flex로 자식한테 높이를 넘겨주라는게 무슨 뜻인지 모르겠습니다

2019-08-21 10:19 UTC, engolder commented on pickin-front/src/pages/SignIn/style.ts
> +  height: 100vh;
ㅇㅇ 마줌 저건 회사이슈얘기인데 무시하셈 height 100으로 하면됨

2019-08-21 11:05 UTC, Chaeeun-Lee commented on pickin-front/src/pages/SignIn/style.ts
> +  border: solid 0.5px #606060;
넵

2019-08-21 11:09 UTC, Chaeeun-Lee commented on pickin-front/src/pages/SignIn/style.ts
> +  background-color: ${mainColor};
#ffffff는 white로 등록돼 있으니까 그냥 white라고 써도 되겠죠?

2019-08-21 11:09 UTC, Chaeeun-Lee commented on pickin-front/src/pages/SignIn/style.ts
> +  & p {
수정하겠습니당

2019-08-21 11:10 UTC, Chaeeun-Lee commented on pickin-front/src/pages/index.ts
> +export { default as SignIn } from "./SignIn";
수정하겠습니다

2019-08-21 11:10 UTC, Chaeeun-Lee commented on pickin-front/src/pages/SignIn/index.tsx
> +    <S.CreateAccountText>Do not have an account?<Link to="/signup"><p>Create Account</p></Link>
그렇더라고요 ㅠ 수정하겠습니다

2019-08-21 11:18 UTC, Chaeeun-Lee commented on pickin-front/src/pages/SignIn/style.ts
> +  height: 100vh;
제 생각에는 app.tsx에 적용시키기 위한 컴포넌트 하나 더 만드는 것보다 그냥 다른 파일들에 100vh 써도 문제 없을 것 같은데 혹시 많이 차이가 나나요?

2019-08-21 11:18 UTC, Chaeeun-Lee commented on pickin-front/src/pages/SignIn/style.ts
> +  opacity: 0.9;
ㅠㅠ 변경하겠습니다

2019-08-26 00:25 UTC, soheejang15 approved these changes

2019-08-27 15:36 UTC, merged